# Generated by Django 4.0.1 on 2022-01-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjoutDeSejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcommande', models.CharField(max_length=255)),
                ('dureeenjour', models.IntegerField()),
                ('versementduclient', models.BooleanField(default=False)),
                ('dateajout', models.DateField(auto_now_add=True)),
                ('statudemande', models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenoms', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(null=True, upload_to='client/image/')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idclient', models.CharField(max_length=255)),
                ('idresidence', models.CharField(max_length=255)),
                ('prixactuel', models.IntegerField()),
                ('dateentree', models.DateField()),
                ('dureeenjour', models.IntegerField()),
                ('versementduclient', models.BooleanField(default=False)),
                ('cleauclient', models.BooleanField(default=False)),
                ('versementauproprio', models.BooleanField(default=False)),
                ('datecommande', models.DateField(auto_now_add=True)),
                ('statucommande', models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NoteResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idclient', models.CharField(max_length=255)),
                ('idresidence', models.CharField(max_length=255)),
                ('note', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (3, '4'), (5, '5')])),
            ],
        ),
    ]
