# Generated by Django 4.0.1 on 2022-01-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='dateentree',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='dureeenjour',
        ),
        migrations.AddField(
            model_name='commande',
            name='datedebut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='datefin',
            field=models.DateField(null=True),
        ),
    ]
